// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfGWf9NLAt-3BIccQQvgcmHvu7tkyT4c0',
    appId: '1:946533401577:web:d9903166cce04f8a2d4178',
    messagingSenderId: '946533401577',
    projectId: 'project1-ae78c',
    authDomain: 'project1-ae78c.firebaseapp.com',
    storageBucket: 'project1-ae78c.firebasestorage.app',
    measurementId: 'G-BW2R6HWD78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXXI3PTXi-pVB8uy0bSWl2BzF4gO6x_w',
    appId: '1:946533401577:android:dbe89992a5a2a3e92d4178',
    messagingSenderId: '946533401577',
    projectId: 'project1-ae78c',
    storageBucket: 'project1-ae78c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZPY_FOJU2lGZ_5qUBlNLmhW9GposJTU',
    appId: '1:946533401577:ios:771c00700b39aa4d2d4178',
    messagingSenderId: '946533401577',
    projectId: 'project1-ae78c',
    storageBucket: 'project1-ae78c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZPY_FOJU2lGZ_5qUBlNLmhW9GposJTU',
    appId: '1:946533401577:ios:771c00700b39aa4d2d4178',
    messagingSenderId: '946533401577',
    projectId: 'project1-ae78c',
    storageBucket: 'project1-ae78c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfGWf9NLAt-3BIccQQvgcmHvu7tkyT4c0',
    appId: '1:946533401577:web:85753f77345a2fb42d4178',
    messagingSenderId: '946533401577',
    projectId: 'project1-ae78c',
    authDomain: 'project1-ae78c.firebaseapp.com',
    storageBucket: 'project1-ae78c.firebasestorage.app',
    measurementId: 'G-VQYHXDVSZZ',
  );
}
